(() => {
  const replacements = [
    // Drivers - longest/specific variants first.
    ['Gabriel Bortoleto', '가브리엘 보르톨레토'],
    ['Kimi Antonelli', '키미 안토넬리'],
    ['Andrea Kimi Antonelli', '키미 안토넬리'],
    ['George Russell', '조지 러셀'],
    ['Charles Leclerc', '샤를 르클레르'],
    ['Lewis Hamilton', '루이스 해밀턴'],
    ['Lando Norris', '랜도 노리스'],
    ['Oscar Piastri', '오스카 피아스트리'],
    ['Max Verstappen', '막스 베르스타펜'],
    ['Isack Hadjar', '아이작 하자르'],
    ['Pierre Gasly', '피에르 가슬리'],
    ['Franco Colapinto', '프랑코 콜라핀토'],
    ['Fernando Alonso', '페르난도 알론소'],
    ['Lance Stroll', '랜스 스트롤'],
    ['Alexander Albon', '알렉스 알본'],
    ['Alex Albon', '알렉스 알본'],
    ['Carlos Sainz', '카를로스 사인츠'],
    ['Liam Lawson', '리암 로슨'],
    ['Arvid Lindblad', '아비드 린드블라드'],
    ['Esteban Ocon', '에스테반 오콘'],
    ['Oliver Bearman', '올리버 베어먼'],
    ['Nico Hulkenberg', '니코 휠켄베르크'],
    ['Nico Hülkenberg', '니코 휠켄베르크'],
    ['Sergio Perez', '세르히오 페레스'],
    ['Sergio Pérez', '세르히오 페레스'],
    ['Valtteri Bottas', '발테리 보타스'],
    ['Yuki Tsunoda', '유키 츠노다'],
    ['Jack Doohan', '잭 두한'],

    // Teams.
    ['Cadillac F1 Team', '캐딜락'],
    ['Alpine F1 Team', '알핀'],
    ['Haas F1 Team', '하스'],
    ['RB F1 Team', '레이싱 불스'],
    ['Red Bull Racing', '레드불 레이싱'],
    ['Racing Bulls', '레이싱 불스'],
    ['Aston Martin', '애스턴 마틴'],
    ['Red Bull', '레드불 레이싱'],
    ['Mercedes', '메르세데스'],
    ['McLaren', '맥라렌'],
    ['Ferrari', '페라리'],
    ['Williams', '윌리엄스'],
    ['Alpine', '알핀'],
    ['Audi', '아우디'],
    ['Cadillac', '캐딜락'],
    ['Haas', '하스'],

    // Race names commonly returned by Jolpica.
    ['Saudi Arabian Grand Prix', '사우디아라비아 그랑프리'],
    ['Emilia Romagna Grand Prix', '에밀리아로마냐 그랑프리'],
    ['United States Grand Prix', '미국 그랑프리'],
    ['Mexico City Grand Prix', '멕시코시티 그랑프리'],
    ['São Paulo Grand Prix', '상파울루 그랑프리'],
    ['Las Vegas Grand Prix', '라스베이거스 그랑프리'],
    ['Australian Grand Prix', '호주 그랑프리'],
    ['Chinese Grand Prix', '중국 그랑프리'],
    ['Japanese Grand Prix', '일본 그랑프리'],
    ['Bahrain Grand Prix', '바레인 그랑프리'],
    ['Miami Grand Prix', '마이애미 그랑프리'],
    ['Monaco Grand Prix', '모나코 그랑프리'],
    ['Spanish Grand Prix', '스페인 그랑프리'],
    ['Canadian Grand Prix', '캐나다 그랑프리'],
    ['Austrian Grand Prix', '오스트리아 그랑프리'],
    ['British Grand Prix', '영국 그랑프리'],
    ['Belgian Grand Prix', '벨기에 그랑프리'],
    ['Hungarian Grand Prix', '헝가리 그랑프리'],
    ['Dutch Grand Prix', '네덜란드 그랑프리'],
    ['Italian Grand Prix', '이탈리아 그랑프리'],
    ['Azerbaijan Grand Prix', '아제르바이잔 그랑프리'],
    ['Singapore Grand Prix', '싱가포르 그랑프리'],
    ['Qatar Grand Prix', '카타르 그랑프리'],
    ['Abu Dhabi Grand Prix', '아부다비 그랑프리'],
    ['Madrid Grand Prix', '마드리드 그랑프리'],

    // Dynamic UI generated by app.js.
    ['SELECTED CONSTRUCTOR', '선택한 팀'],
    ['SELECTED DRIVER', '선택한 드라이버'],
    ['NO RIVAL', '경쟁자 없음'],
    ['ADVANTAGE', '현재 우위'],
    ['TRAILING', '현재 열세'],
    ['ELIMINATED', '수학적 탈락'],
    ['SELECTED', '선택'],
    ['ALIVE', '경쟁 중'],
    ['Race P1', '레이스 우승'],
    ['Race P2', '레이스 2위'],
    ['Race P3', '레이스 3위'],
    ['Quali P1', '퀄리파잉 1위'],
    ['Last updated', '업데이트'],
    ['Final round', '최종전'],
    ['Constructors', '팀'],
    ['Drivers', '드라이버'],
    ['Constructor', '팀'],
    ['Driver', '드라이버'],
    ['countback', '카운트백'],
    ['Countback', '카운트백'],
    ['Sprint', '스프린트'],
    ['Magic', '매직넘버'],
    ['Max Final', '가능 최대점'],
    ['Status', '상태'],
    ['Gap', '격차'],
    ['Pts', '포인트'],
    ['Pos', '순위'],
    ['TIED', '동점'],
    ['OUT', '탈락'],
    [' pts', '점']
  ];

  const labelMap = {
    Pos: '순위', Driver: '드라이버', Constructor: '팀', Pts: '포인트', Gap: '격차',
    'Max Final': '가능 최대점', Magic: '매직넘버', Status: '상태'
  };

  function translateString(input) {
    let value = input;
    for (const [from, to] of replacements) value = value.split(from).join(to);
    value = value.replace(/\bRound\s+(\d+)/g, '$1라운드');
    value = value.replace(/\bP(\d+)\b/g, '$1위');
    return value;
  }

  function translateTextNode(node) {
    if (!node.nodeValue || !node.nodeValue.trim()) return;
    const next = translateString(node.nodeValue);
    if (next !== node.nodeValue) node.nodeValue = next;
  }

  function translateElement(element) {
    if (!(element instanceof Element)) return;
    if (element.hasAttribute('data-label')) {
      const label = element.getAttribute('data-label');
      const next = labelMap[label] || translateString(label || '');
      if (next && next !== label) element.setAttribute('data-label', next);
    }
    if (element.tagName === 'OPTION' && element.textContent) {
      const next = translateString(element.textContent);
      if (next !== element.textContent) element.textContent = next;
    }
  }

  function translateTree(root) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) {
      translateTextNode(root);
      return;
    }
    if (root.nodeType === Node.ELEMENT_NODE) translateElement(root);
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
    let node;
    while ((node = walker.nextNode())) {
      if (node.nodeType === Node.TEXT_NODE) translateTextNode(node);
      else translateElement(node);
    }
  }

  translateTree(document.body);

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === 'characterData') translateTextNode(mutation.target);
      for (const node of mutation.addedNodes) translateTree(node);
    }
  });
  observer.observe(document.body, { childList: true, subtree: true, characterData: true });
})();
